test: unit tests covering exclude_bad_drafts.py
YangCatalog/sdo_analysis pull request #185
Opened 2022-08-02 10:51 UTC by SlavomirMazurPantheon

Signed-off-by: Slavomir Mazur <slavomir.mazur@pantheon.tech>

2022-08-03 09:35 UTC, richardzilincikPantheon requested changes

2022-08-03 09:35 UTC, richardzilincikPantheon commented on bin/exclude_bad_drafts.py
> +        bash_command = 'rm -f {} {}'.format(directory, line)
This wouldn't work, there shouldn't be a space between the directory and the filename. It would be cleaner to call `os.remove()` instead.

2022-08-03 13:12 UTC, SlavomirMazurPantheon commented
After some review it seems that functionality of this script is no longer needed - I changed this PR, it will remove script, its calls and all necessary files.

2022-08-05 08:10 UTC, richardzilincikPantheon approved these changes

2022-08-05 08:43 UTC, merged