Notify authors of ietf drafts
YangCatalog/sdo_analysis pull request #197
Opened 2022-09-12 09:48 UTC by Fagtoy

Added email sending for authors of new problematic drafts.
I am not sure about the solution with the use of destructor in MessageFactory class, maybe it would be better to use a context manager here.
Messages look like this:
![image](https://user-images.githubusercontent.com/60445869/189622150-d9643232-7876-4ceb-b1fc-26d7d7bcf3b6.png)
I'm also not sure about the extraction of author names from draft files names because following [this](https://github.com/YangCatalog/sdo_analysis/blob/master/bin/metadata_generators/draft_metadata_generator.py#L22) example locally I get something like ```draft-ietf-netconf-keystore-25``` as can be seen above

resolves #194

2022-09-12 10:35 UTC, richardzilincikPantheon requested changes
These emails would be sent to people that don't about this functionality, so it would be useful to add a one line explanation of why they're receiving the email. I think YANG Catalog should also be mentioned in the subject.

2022-09-12 10:35 UTC, richardzilincikPantheon commented on bin/extractors/dratf_extractor.py
> +            json.dump(self.drafts_missing_code_section, writer)
This looks like it would only keep the error from the latest run. We want to keep the errors from previous runs as well.

2022-09-12 10:35 UTC, richardzilincikPantheon commented on bin/message_factory/message_factory.py
> +        self.close_connection_after_message_sending = close_connection_after_message_sending
This should also be prefixed with an underscore. If this got manually modified after the initialization, the smtp connection could stay open after the MessageFactory is destructed.

2022-09-12 10:36 UTC, richardzilincikPantheon commented on bin/extractors/dratf_extractor.py
> +            json.dump(self.drafts_missing_code_section, writer)
Actually never mind, all the errors should get generated on every run anyway.

2022-09-12 10:47 UTC, Fagtoy commented
> These emails would be sent to people that don't about this functionality, so it would be useful to add a one line explanation of why they're receiving the email. I think YANG Catalog should also be mentioned in the subject.

added some explanation

2022-09-12 11:09 UTC, richardzilincikPantheon approved these changes

2022-09-12 11:12 UTC, richardzilincikPantheon commented
NOTE: needs to be deployed after xym is updated.

2022-09-19 17:46 UTC, SlavomirMazurPantheon commented
How often will these emails be sent? When new draft is detected? 
I would prefer something like sending it once a month to all the authors of drafts which were identified.
This can be added do the `crontab` file and comment it out for now so we can also merge this and not wait for xym release.

2022-09-20 05:25 UTC, richardzilincikPantheon commented
I think it makes more sense to send them when a new draft is processed. In some cases, a new draft revision may be made more than once a month. On the other hand, sometimes there is more than a year between new revisions, and I don't think it would be great to send the the same email 12+ times. If we only do it once a month, the feedback will be on average delayed by 15 days instead of next day.

2022-09-20 06:14 UTC, SlavomirMazurPantheon commented
Okay, no problem then.

2022-09-29 11:11 UTC, SlavomirMazurPantheon commented
Merging this PR now - functionality stays disabled by flag `send_emails_about_problematic_drafts` in config file

2022-09-29 11:12 UTC, merged