check_archived_drafts.py attempting to use nonexistent directory
YangCatalog/sdo_analysis pull request #222
Opened 2022-11-01 12:51 UTC by dmytro-kyrychenko

2022-11-03 07:49 UTC, richardzilincikPantheon approved these changes

2022-11-04 08:56 UTC, SlavomirMazurPantheon requested changes

2022-11-04 08:56 UTC, SlavomirMazurPantheon commented on bin/check_archived_drafts.py
> +        os.makedirs(all_yang_path)
you can use `os.makedirs(all_yang_path, exist_ok=True)` instead of checking whether dir already exists

2022-11-04 08:56 UTC, SlavomirMazurPantheon commented on bin/check_archived_drafts.py
> +        os.rmdir(all_yang_path)
Again, you can use `shutil.rmtree(all_yang_path, ignore_errors=True)` so `FileNotFoundError` is ignored.
Then you don't need to use `remove_all_yang_path` temp variable at all.

2022-11-04 11:49 UTC, SlavomirMazurPantheon approved these changes

2022-11-04 11:50 UTC, merged