fix: restructured ```yang_get_stats.py``` script and fixed the problem with YANGPageMain_ prefix
YangCatalog/sdo_analysis pull request #224
Opened 2022-11-02 15:21 UTC by Fagtoy

Restructured the ```yang_get_stats.py``` script, so there's only one iteration through all the files in which we gather stats for every file that contains one of the prefixes. I also fixed the issue about filenames containing some prefixes, so for now a file with the name "IETFYANGPageMain_2022_01_01.html" won't be considered as the file whose name contains the "YANGPageMain_" prefix if we also look for the files with the "IETFYANGPageMain_" prefix

resolves #223

2022-11-03 08:25 UTC, richardzilincikPantheon requested changes

2022-11-03 08:25 UTC, richardzilincikPantheon commented on bin/yang_get_stats.py
> +            if prefix.lower() not in filename:
`filename.startswith(prefix.lower())` would probably be better here, assuming we don't rely on matching "prefixes" in the middle of the filename.

2022-11-03 10:02 UTC, richardzilincikPantheon approved these changes

2022-11-04 09:01 UTC, SlavomirMazurPantheon approved these changes

2022-11-04 09:01 UTC, merged